name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      blogId:
        description: '输入数字id'
        type: number
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "env=${{ github.event.inputs.env }}"
          echo "version=${{ github.event.inputs.version }}"
