name: Workflow Call Level H

on:
  workflow_call:

permissions: {}

jobs:
  run-level-h-task:
    name: Level H independent task
    runs-on: ubuntu-latest
    steps:
      - run: echo "Independent task completed at level H"

  call-level-i:
    name: Level H calls I
    uses: ./.github/workflows/workflow-call-level-i.yml
