name: Workflow Call 10 Levels (A)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/workflow-call-level-*.yml"

permissions: {}

jobs:
  call-level-b:
    name: Level A calls B
    uses: ./.github/workflows/workflow-call-level-b.yml
